"""Deterministic recap generation for the Course Recap Generator web app.

Extraction reuses the pdf_extractor MCP server's helpers (imported
from mcp-servers/pdf-extractor/server.py) so the web app and the
MCP tools produce identical extraction results.

The recap itself is generated by templates and heuristics — it is
EXTRACTIVE: it arranges sentences and headings that appear in the
source. It does NOT use an LLM. For a faithful, LLM-authored recap
(course-recap skill templates + course-reviewer sub-agent pass),
run the OpenCode pipeline instead.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "mcp-servers" / "pdf-extractor"))

from server import _normalize_metadata, _read_pdf, _walk_outline  # noqa: E402

SCANNED_PAGE_CHAR_THRESHOLD = 20
GENERIC_SLIDE_RE = re.compile(r"^(slide|page)\s*\d+$", re.IGNORECASE)
SENTENCE_RE = re.compile(r"[^.!?]+[.!?]")
DEFINITION_SIGNALS = (
    " is ", " are ", " means", "defined as", "refers to", "called",
    "formula", "example", "used for", "helps", "ensures",
)
KEYWORD_SIGNALS = DEFINITION_SIGNALS + (
    "explores", "learns", "groups", "predict", "working",
    "advantages", "disadvantages",
)
MAX_CONCEPTS = 15


# ---------------------------------------------------------------- extraction

def extract_pdf(pdf_path: Path) -> dict:
    """Same per-page extraction + outline walk as the MCP server,
    applied to an arbitrary (uploaded) file path."""
    reader = _read_pdf(pdf_path)
    pages: list[dict] = []
    warnings: list[str] = []
    total_chars = 0

    for index, page in enumerate(reader.pages, start=1):
        text = page.extract_text() or ""
        char_count = len(text.strip())
        total_chars += char_count
        entry = {"page": index, "char_count": char_count, "text": text}
        if char_count < SCANNED_PAGE_CHAR_THRESHOLD:
            warning = (
                f"page {index}: little or no extractable text "
                "(likely image-only/scanned)"
            )
            entry["warning"] = warning
            warnings.append(warning)
        pages.append(entry)

    try:
        outline = _walk_outline(reader.outline, reader)
        outline_warning = None
    except Exception as exc:  # malformed outline
        outline, outline_warning = [], f"outline could not be read: {exc}"

    return {
        "ok": True,
        "page_count": len(reader.pages),
        "metadata": _normalize_metadata(reader.metadata),
        "total_chars": total_chars,
        "warnings": warnings,
        "pages": pages,
        "outline": outline,
        "outline_warning": outline_warning,
    }


# ------------------------------------------------------------- text helpers

def _sentences(text: str) -> list[str]:
    flat = re.sub(r"\s+", " ", text).strip()
    return [s.strip() for s in SENTENCE_RE.findall(flat) if len(s.strip()) >= 30]


def _score_sentence(sentence: str, position: int) -> int:
    low = sentence.lower()
    score = sum(2 for kw in KEYWORD_SIGNALS if kw in low)
    if 40 <= len(sentence) <= 280:
        score += 1
    if position == 0:
        score += 1
    return score


def _key_sentences(text: str, limit: int = 6) -> list[str]:
    sents = _sentences(text)
    scored = sorted(
        ((_score_sentence(s, i), i, s) for i, s in enumerate(sents)),
        key=lambda t: (-t[0], t[1]),
    )
    return [s for _, _, s in scored[:limit]]


def _looks_like_heading(line: str) -> bool:
    line = line.strip()
    if not line or len(line) > 90 or line.endswith((".", ":", ";", ",")):
        return False
    if re.match(r"^(Q\d+[\)\.]|\d+[\)\.])\s*", line, re.IGNORECASE):
        return True
    words = [w for w in line.split() if len(w) > 2]
    if not words:
        return False
    capitalized = sum(1 for w in words if w[0].isupper())
    return capitalized / len(words) >= 0.6


def _kebab(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:60] or "concept"


def _clean_title(title: str) -> str:
    t = re.sub(
        r"^(Q\d+|Chapter\s+\d+|Unit\s+\d+|Section\s+\d+|Module\s+\d+|Slide\s+\d+)"
        r"[\)\.:]?\s*",
        "",
        title,
        flags=re.IGNORECASE,
    )
    return t.strip().rstrip("?").strip()[:80] or "Untitled section"


def _page_range(pages: list[int]) -> str:
    start, end = pages[0], pages[-1]
    return str(start) if start == end else f"{start}–{end}"


def _clean_module_text(
    text: str, headings: list[str], doc_title: str
) -> str:
    """Flatten whitespace and strip all section headings and the
    document header, so extracted sentences don't start with
    title preamble."""
    flat = re.sub(r"\s+", " ", text)
    for fragment in [doc_title, *headings]:
        if fragment:
            flat = flat.replace(fragment, " ")
    return flat


# ------------------------------------------------------------ module split

def _split_modules(pages: list[dict], outline: list[dict]) -> list[dict]:
    """Derive modules from the outline (when it has real titles),
    else from detected headings, else one module per page."""
    real = [
        e for e in outline
        if e.get("title") and not GENERIC_SLIDE_RE.match(e["title"].strip())
    ]
    if real:
        modules = []
        for i, entry in enumerate(real):
            start = entry.get("page") or 1
            end = (real[i + 1].get("page") or pages[-1]["page"]) \
                if i + 1 < len(real) else pages[-1]["page"]
            text = "\n".join(
                p["text"] for p in pages if start <= p["page"] <= end
            )
            # truncate at the next outline title when both share text
            if i + 1 < len(real):
                next_title = real[i + 1]["title"].strip()
                cut = text.find(next_title)
                if cut > 0:
                    text = text[:cut]
            modules.append({
                "title": entry["title"].strip(),
                "pages": list(range(start, end + 1)),
                "depth": entry.get("depth", 0),
                "text": text,
            })
        return modules

    modules: list[dict] = []
    current: dict | None = None
    for p in pages:
        for line in p["text"].splitlines():
            if _looks_like_heading(line):
                if current:
                    modules.append(current)
                current = {
                    "title": line.strip(),
                    "pages": [p["page"]],
                    "depth": 0,
                    "text": "",
                }
            elif current is not None:
                current["text"] += line + "\n"
                current["pages"].append(p["page"])
    if current:
        modules.append(current)

    if not modules:  # fallback: one module per page
        modules = [{
            "title": f"Page {p['page']}",
            "pages": [p["page"]],
            "depth": 0,
            "text": p["text"],
        } for p in pages]
    return modules


# ------------------------------------------------------------ recap building

def generate_recap(extraction: dict, filename: str = "uploaded.pdf") -> dict:
    """Build the full deterministic recap from an extraction result."""
    pages = extraction.get("pages", [])
    outline = extraction.get("outline", [])
    metadata = extraction.get("metadata", {})

    # --- document title (metadata title, else first lines of page 1)
    first_lines: list[str] = []
    for line in (pages[0]["text"].splitlines() if pages else []):
        line = line.strip()
        if line:
            first_lines.append(line)
        if len(first_lines) >= 2:
            break
    head_candidate = " ".join(first_lines)
    doc_title = (
        metadata.get("title")
        or (head_candidate
            if 4 <= len(head_candidate) <= 80 and "." not in head_candidate
            else "")
        or (outline[0]["title"].strip() if outline else "")
        or "Uploaded course PDF"
    )[:120]

    modules = _split_modules(pages, outline)
    all_headings = [m["title"] for m in modules]

    # --- concepts (one per module, capped)
    concepts: list[dict] = []
    seen_ids: set[str] = set()
    for m in modules[:MAX_CONCEPTS]:
        title = _clean_title(m["title"])
        concept_id = _kebab(title)
        if concept_id in seen_ids:
            concept_id = f"{concept_id}-{len(seen_ids) + 1}"
        seen_ids.add(concept_id)

        body = _clean_module_text(m["text"], all_headings, doc_title)
        definition = ""
        for s in _sentences(body):
            if any(sig in s.lower() for sig in DEFINITION_SIGNALS):
                definition = s
                break
        if not definition:
            sents = _sentences(body)
            definition = sents[0] if sents else \
                "(no extractable definition — see source pages)"

        concepts.append({
            "concept": concept_id,
            "title": title,
            "definition": definition,
            "pages": _page_range(m["pages"]),
            "why": "Topic section in the source document",
        })

    # --- diagram: outline depth → "includes" edges, else sequential chain
    diagram_lines = ["flowchart TD"]
    edges: list[str] = []
    last_root: str | None = None
    for i, c in enumerate(concepts):
        label = c["title"][:48].replace('"', "'")
        diagram_lines.append(f'    {c["concept"]}["{label}"]')
        depth = modules[i].get("depth", 0) if i < len(modules) else 0
        if depth == 0:
            if last_root:
                edges.append(f'    {last_root} -->|"next"| {c["concept"]}')
            last_root = c["concept"]
        elif last_root:
            edges.append(f'    {last_root} -->|"includes"| {c["concept"]}')
    diagram_lines.extend(edges)
    if not concepts:
        diagram_lines.append('    no-content["No concepts extracted"]')
    diagram = "\n".join(diagram_lines)

    # --- overview
    topic_list = ", ".join(c["title"] for c in concepts[:5])
    overview = (
        f"{doc_title} is a {extraction['page_count']}-page document with "
        f"{extraction['total_chars']:,} characters of extractable text, "
        f"covering {len(concepts)} topic(s): {topic_list}. "
        "This recap was generated automatically by extractive templates — "
        "it arranges the source's own headings and sentences without an LLM. "
        "For a faithful, LLM-authored recap with a reviewer pass, run the "
        "OpenCode pipeline (course-recap skill + course-reviewer sub-agent)."
    )

    return {
        "ok": True,
        "filename": filename,
        "title": doc_title,
        "page_count": extraction["page_count"],
        "total_chars": extraction["total_chars"],
        "warnings": extraction.get("warnings", []),
        "overview": overview,
        "objectives": [f"Understand: {m['title']}" for m in modules[:8]],
        "modules": [{
            "title": m["title"],
            "pages": _page_range(m["pages"]),
            "takeaways": _key_sentences(
                _clean_module_text(m["text"], all_headings, doc_title)
            ),
        } for m in modules],
        "glossary": [{
            "term": c["title"],
            "definition": c["definition"],
            "pages": c["pages"],
        } for c in concepts[:12]],
        "self_check": [f"What is {c['title']}?" for c in concepts[:5]]
        + ["What are the main topics covered in this document?"],
        "concepts": concepts,
        "diagram": diagram,
        "note": (
            "Deterministic extractive draft (no LLM). "
            f"{len(modules)} module(s) derived from "
            + ("the PDF outline" if outline else "detected headings")
            + ("; concepts capped at 15" if len(modules) > MAX_CONCEPTS else "")
        ),
        "extraction": {
            "page_count": extraction["page_count"],
            "metadata": metadata,
            "total_chars": extraction["total_chars"],
            "warnings": extraction.get("warnings", []),
            "outline": outline,
        },
    }
